network.host: 0.0.0.0
http.port: 9200
cluster.name: elk-cluster
node.name: ${HOSTNAME}
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false
