
# Kibana server configuration
server.port: 5601
# Prefer IPv6 and listen on all interfaces
server.host: "::"

# Elasticsearch connection
# Prefer IPv6 loopback
elasticsearch.hosts: ["http://[::1]:9200"]
